### ISSUE TITLE
Can we use DB for sharing customer charging information

### ISSUE THREAD

**Issue by kishiguro** [free5gc/chf#12]
@brianchennn Hi, I have a question about current architecture of CHF.  It seems we are using file for sharing each subscriber charging informaition.  I'm wonding is there any specific reason of not using Database for it.

**Comment by brianchennn** [comment]
It's not my design. May be we should ask @Roy-Hu

**Comment by brianchennn** [comment]
@kishiguro 
CDR File is defined in TS 32.297. So I think it's OK to use file system to store Charging Data Record (CDR).
Now the CDR transport scenario is :
![image](https://github.com/free5gc/chf/assets/46628572/4906e34c-060c-4481-b43d-d6999d5fb9f2)

**Comment by kishiguro** [comment]
@brianchennn @Roy-Hu Thanks for the detailed explanation.  I understand current implemetation confirmes to the standard.
