### ISSUE TITLE
Export chf image to docker hub

### ISSUE THREAD

**Issue by eliasmainetti** [free5gc/chf#4]
Hi Guys, 

Could you please push chf image to docker hub? 

<img width="985" alt="image" src="https://github.com/free5gc/chf/assets/34216013/3865525f-0af6-40bb-bdb9-174289dc392c">

**Comment by ianchen0119** [comment]
Hi @eliasmainetti 

We're currently working on the integration work.
We will release the CHF's docker image in the incoming release.

Thank you.
